# -*- coding: utf-8 -*-
"""column transform Working.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fHV7Ru66NH-rfWGHuN0PAvDFB8fuPO9M
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

df = pd.read_csv("credit_scoring.csv")

# Identify columns that might contain '\n' and need to be expanded
# These are typically object type columns
for col in df.columns:
    if df[col].dtype == 'object' and df[col].astype(str).str.contains('\n').any():
        df = df.assign(**{col: df[col].str.split('\n')}).explode(col)

# Convert 'Age' and 'Credit Utilization' to numeric after cleaning
df['Age'] = pd.to_numeric(df['Age'])
df['Credit Utilization'] = pd.to_numeric(df['Credit Utilization'])

df.head(3)

from sklearn.model_selection import train_test_split
# Ensure the target column 'Credit Utilization' is correctly separated from features.
# It should be dropped from X and used as y.
X_train, X_test, y_train, y_test = train_test_split(
    df.drop(columns=['Credit Utilization']),
    df['Credit Utilization'],
    test_size=0.2,
    random_state=42 # Added for reproducibility
)
X_train.head()

df.isnull().sum()

# Define numerical and categorical features
numerical_features = ['Age']
categorical_features = ['Gender', 'Marital Status', 'Education Level', 'Employment Sta']

# Create preprocessing pipelines for numerical and categorical features
numerical_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Combine preprocessing steps using ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Create a full preprocessing pipeline
# This pipeline will transform the X_train and X_test data
# No model is added yet, as the prompt is about preprocessing
preprocessing_pipeline = Pipeline(steps=[('preprocessor', preprocessor)])

# Fit and transform the training data
X_train_processed = preprocessing_pipeline.fit_transform(X_train)

# Transform the test data
X_test_processed = preprocessing_pipeline.transform(X_test)

print("Shape of processed X_train:", X_train_processed.shape)
print("Shape of processed X_test:", X_test_processed.shape)

from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[['Unemployed', 'Employed', 'Self-Employed']])

df[['Employment Sta']] = oe.fit_transform(df[['Employment Sta']])

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

transformer = ColumnTransformer(
    transformers=[
        ('gender', OneHotEncoder(sparse_output=False, drop='first'), ['Gender'])
    ],
    remainder='passthrough'
)

X_transformed = transformer.fit_transform(df)

X_train_transformed = transformer.fit_transform(X_train)

print(X_train_transformed.shape)

print(transformer.transform(X_test))

